# this should be very similar to https://github.com/conda-forge/amsthm-feedstock/blob/master/recipe/meta.yaml
# run the following command to create a conda environment that is suitable for testing amsthm
# conda env create -f environment.yml
# conda activate amsthm
# python -m ipykernel install --user --name amsthm --display-name amsthm
# and then run this to install amsthm in editable mode
# make editable
# update using
# conda env update --name amsthm --file environment.yml --prune
name: amsthm
channels:
  - conda-forge
dependencies:
  # host:
  - pip
  - python >=3.8
  - poetry >=1,<2
  # run:
  # run_constrained:
  - coloredlogs >=14,<16
  # tests:
  - coverage
  - coveralls
  - pytest
  - pytest-parallel >=0.1.1,<0.2
  # docs:
  - sphinx
  - sphinx_bootstrap_theme
  - sphinxcontrib-apidoc
  # dev:
  - pandoc
  - isort
  - mypy
  - bandit
  - black
  - bump2version
  - ghp-import >=2,<3
  - nbconvert >=6,<7
  - pylint
  - rstcheck
  - types-pyyaml
