SHELL = /usr/bin/env bash

_python ?= python
# for `uv version --bump`, valid options are: major, minor, patch
PART ?= patch

PANDOC = pandoc
pandocArgs = --toc -M date="`date "+%B %e, %Y"`" --wrap=none
RSTs = CHANGELOG.rst README.rst docs/example-output.rst

# Main Targets #################################################################

.PHONY: docs api html linkcheck test clean

docs: $(RSTs)
	$(MAKE) html
api: docs/api/
html: dist/docs/
linkcheck:
	sphinx-build -b linkcheck docs dist/linkcheck

test:
	rm -f .coverage*
	$(_python) -m coverage run -m pytest -vv tests
coverage: test
	coverage combine; coverage report
	coverage html
	coverage xml

clean:
	rm -f $(RSTs) .coverage* tests/model-latex.pdf tests/model-html.html

# docs #########################################################################

README.rst: docs/README.md
	printf \
		"%s\n\n" \
		".. This is auto-generated from \`$<\`. Do not edit this file directly." \
		> $@
	$(PANDOC) $(pandocArgs) $< -V title='pandoc-amsthm Documentation' -s -t rst -o $@

%.rst: %.md
	printf \
		"%s\n\n" \
		".. This is auto-generated from \`$<\`. Do not edit this file directly." \
		> $@
	$(PANDOC) $(pandocArgs) $< -s -t rst >> $@

docs/api/:
	sphinx-apidoc \
		--maxdepth 6 \
		--force \
		--separate \
		--module-first \
		--implicit-namespaces \
		--doc-project API \
		--output-dir $@ src/amsthm

dist/docs/:
	sphinx-build -E -b dirhtml docs dist/docs

# maintenance ##################################################################

.PHONY: build bump
build:
	rm -rf dist
	uv build

print-%:
	$(info $* = $($*))

# releasing ####################################################################

# bump version, commit, tag, and push; pushing the tag triggers the release workflow
bump:
	uv version --bump $(PART) --frozen
	git commit -am "Bump version: $$(uv version --short)"
	git tag "v$$(uv version --short)"
	git push --follow-tags

# test files ###################################################################

target: tests/model-target.md tests/model-latex.tex
demo: tests/model-latex.pdf tests/model-html.html

tests/model-target.md: tests/model-source.md
	pandoc -F amsthm $< -o $@
tests/model-latex.tex: tests/model-source.md
	pandoc -F amsthm $< -o $@ --top-level-division=chapter --toc -N
tests/model-latex.pdf: tests/model-source.md
	pandoc -F amsthm $< -o $@ --top-level-division=chapter --toc -N
tests/model-html.html: tests/model-source.md
	pandoc -F amsthm $< -o $@ --toc -N -s
docs/example-output.rst: tests/model-source.md
	pandoc -F amsthm $< -o $@ --toc -N -s
